allowBuilds:
  '@firebase/util': false
  esbuild: false
  protobufjs: false
  re2: true
  workerd: true
minimumReleaseAgeExclude:
  - '@kubohiroya/vite-plugin-turbowarp-extension@0.1.0 || 0.4.0'
  - '@kubohiroya/turbowarp-named-data@0.1.0'
  - '@cloudflare/workers-types@5.20260919.1'
  - '@kubohiroya/turbowarp-named-data@0.2.0'
  - miniflare@5.20260918.0-alpha
  - wrangler@4.135.0
