import {canonicalizeDeployIrV2} from '../ir-v2/canonical.js';
import type {DeployIrV2} from '../ir-v2/types.js';
import type {GeneratedCore} from './types.js';

export function generateHonoCore(ir: DeployIrV2): GeneratedCore {
  return {
    entryModule: './core.generated.js',
    files: {'src/core.generated.ts': coreSource(ir)}
  };
}

function coreSource(ir: DeployIrV2): string {
  return `// Generated by turbowarp-http-server. Platform-neutral Hono core.
import type {Hono} from 'hono';

type StoredRecord = Record<string, unknown>;
export interface RecordStore {
  create(collection: string, data: unknown): Promise<StoredRecord>;
  list(collection: string): Promise<StoredRecord[]>;
  get(id: string): Promise<StoredRecord | null>;
  delete(id: string): Promise<boolean>;
}
export interface CoreServices {
  records?: (context: unknown) => RecordStore;
  clientAddress?: (context: unknown) => string;
}
type App = Hono<any>;
const ir: any = ${canonicalizeDeployIrV2(ir)};

export function registerCoreRoutes(app: App, services: CoreServices): void {
  for (const route of ir.routes) {
    const method = route.method === 'ALL' ? 'all' : route.method.toLowerCase();
    (app as any)[method](route.path, async (c: any) => executeRoute(route, c, services));
  }
}

async function executeRoute(route: (typeof ir.routes)[number], c: any, services: CoreServices): Promise<Response> {
  let status = 200;
  const headers = new Headers();
  const bindings = new Map<string, unknown>();
  const handlerVariables = new Map<string, string>();
  let bodyText: string | undefined;
  try {
    for (const statement of route.body) {
      if (statement.kind === 'set-status') status = statement.status;
      else if (statement.kind === 'set-header') setResponseHeader(headers, statement.name, asText(await expression(statement.value)));
      else if (statement.kind === 'remove-header') headers.delete(statement.name);
      else if (statement.kind === 'set-handler-variable') {
        handlerVariables.set(asText(await expression(statement.name)), asText(await expression(statement.value)));
      } else if (statement.kind === 'change-handler-variable') {
        const name = asText(await expression(statement.name));
        handlerVariables.set(name, String(scratchNumber(handlerVariables.get(name) ?? '') + scratchNumber(await expression(statement.value))));
      } else if (statement.kind === 'delete-handler-variable') {
        handlerVariables.delete(asText(await expression(statement.name)));
      } else if (statement.kind === 'clear-handler-variables') handlerVariables.clear();
      else if (statement.kind === 'record-create') {
        bindings.set(statement.result.id, await requiredRecords().create(statement.collection, await expression(statement.data)));
      } else if (statement.kind === 'record-list') {
        bindings.set(statement.result.id, await requiredRecords().list(statement.collection));
      } else if (statement.kind === 'record-get') {
        bindings.set(statement.result.id, await requiredRecords().get(asText(await expression(statement.id))));
      } else if (statement.kind === 'record-delete') {
        bindings.set(statement.result.id, await requiredRecords().delete(asText(await expression(statement.id))));
      } else if (statement.kind === 'respond') {
        return response(statement.format, await expression(statement.body), status, headers);
      } else throw runtimeError('IR_OPERATION_UNSUPPORTED');
    }
    throw runtimeError('IR_MISSING_RESPONSE');
  } catch (error) {
    const fault = runtimeFault(error);
    return new Response(JSON.stringify({error: {code: fault.code}}), {status: fault.status, headers: {'content-type': 'application/json; charset=utf-8'}});
  }

  async function expression(value: any): Promise<unknown> {
    if (value.kind === 'literal') return value.value;
    if (value.kind === 'binding') return bindings.get(value.binding);
    if (value.kind === 'concat') return asText(await expression(value.left)) + asText(await expression(value.right));
    if (value.kind === 'handler-variable') return handlerVariables.get(asText(await expression(value.name))) ?? '';
    if (value.kind === 'handler-variable-exists') return handlerVariables.has(asText(await expression(value.name)));
    if (value.kind === 'handler-variable-names') return [...handlerVariables.keys()].join(',');
    if (value.kind === 'request-value') {
      if (value.source === 'query') return c.req.query(value.name) ?? '';
      if (value.source === 'path-param') return c.req.param(value.name) ?? '';
      return c.req.header(value.name) ?? '';
    }
    if (value.kind === 'request') {
      if (value.source === 'method') return c.req.method;
      if (value.source === 'path') return new URL(c.req.url).pathname;
      if (value.source === 'url') return c.req.url;
      if (value.source === 'body-text') return (bodyText ??= await c.req.text());
      if (value.source === 'content-type') return c.req.header('content-type') ?? '';
      return services.clientAddress?.(c) ?? '';
    }
    throw runtimeError('IR_EXPRESSION_UNSUPPORTED');
  }
  function requiredRecords(): RecordStore {
    if (!services.records) throw runtimeError('IR_CAPABILITY_UNAVAILABLE');
    return services.records(c);
  }
}

class IrRuntimeError extends Error {
  constructor(readonly code: string, readonly status: number) {super(code)}
}
function runtimeError(code: string, status = 500): IrRuntimeError {return new IrRuntimeError(code, status)}
function runtimeFault(error: unknown): {code: string; status: number} {
  if (error instanceof IrRuntimeError) return {code: error.code, status: error.status};
  if (typeof error !== 'object' || error === null || !('code' in error) || typeof error.code !== 'string') {
    return {code: 'IR_RUNTIME_ERROR', status: 500};
  }
  const status = KNOWN_RUNTIME_STATUS[error.code];
  return status === undefined ? {code: 'IR_RUNTIME_ERROR', status: 500} : {code: error.code, status};
}
const KNOWN_RUNTIME_STATUS: Readonly<Record<string, number>> = {
  INVALID_JSON: 422,
  INVALID_PATH: 422,
  PATH_NOT_FOUND: 422,
  TYPE_MISMATCH: 422,
  INDEX_OUT_OF_RANGE: 422,
  ITERATION_LIMIT_EXCEEDED: 422,
  ITERATION_CONTEXT_REQUIRED: 422,
  BINARY_INVALID_REF: 422,
  BINARY_NOT_FOUND: 404,
  BINARY_TOO_LARGE: 413,
  BINARY_INTEGRITY_MISMATCH: 502,
  BINARY_BODY_CONSUMED: 500,
  BINARY_STORAGE_FAILURE: 502
};
function asText(value: unknown): string {return typeof value === 'string' ? value : JSON.stringify(value)}
function scratchNumber(value: unknown): number {
  const number = Number(value);
  return Number.isNaN(number) ? 0 : number;
}
function setResponseHeader(headers: Headers, name: string, value: string): void {
  if (!/[\\r\\n]/u.test(value)) headers.set(name, value);
}
function response(format: 'text' | 'html' | 'json', value: unknown, status: number, headers: Headers): Response {
  if (!headers.has('content-type')) headers.set('content-type', format === 'json' ? 'application/json; charset=utf-8' : format === 'html' ? 'text/html; charset=utf-8' : 'text/plain; charset=utf-8');
  const body = format === 'json' ? JSON.stringify(value) : asText(value);
  return new Response(body, {status, headers});
}
`;
}
