import type {ActionIr, AuthMode, DeployIr, ExpressionIr, RouteIr} from './ir.js';

export type GeneratedFiles = Record<string, string>;

export function generateCloudflareWorker(ir: DeployIr): GeneratedFiles {
  return {
    'package.json': packageJson(ir),
    'tsconfig.json': tsconfig(),
    'src/index.ts': indexSource(),
    'src/routes.generated.ts': routesSource(ir),
    'src/auth.ts': authSource(),
    'src/storage.ts': storageSource(),
    'wrangler.jsonc': wrangler(ir),
    'migrations/0001_init.sql': migration(),
    '.dev.vars.example': devVars(ir.auth),
    '.gitignore': '.dev.vars\nnode_modules/\n.wrangler/\ndist/\n',
    'README.md': generatedReadme(ir)
  };
}

function routesSource(ir: DeployIr): string {
  const routes = ir.routes.map((route) => routeSource(route, ir.auth)).join('\n\n');
  return `// Generated by turbowarp-http-server. Do not edit manually.
import type {Hono} from 'hono';
import {authenticate} from './auth';
import type {AuthUser} from './auth';
import {createRecord, deleteRecord, getRecord, listRecords} from './storage';

export type Bindings = {
  DB: D1Database;
  ASSETS?: R2Bucket;
  CONFIG?: KVNamespace;
  CF_ACCESS_TEAM_DOMAIN?: string;
  CF_ACCESS_AUD?: string;
  JWT_ISSUER?: string;
  JWT_AUDIENCE?: string;
  JWT_JWKS_URL?: string;
};

export type Variables = {authUser: AuthUser | null};
type App = Hono<{Bindings: Bindings; Variables: Variables}>;

export function registerGeneratedRoutes(app: App): void {
${indent(routes, 2)}
}

function asText(value: unknown): string {
  return typeof value === 'string' ? value : JSON.stringify(value);
}

function scratchNumber(value: unknown): number {
  const number = Number(value);
  return Number.isNaN(number) ? 0 : number;
}

function authUserId(user: AuthUser | null): string | undefined {
  return user?.id;
}

function setResponseHeader(headers: Headers, name: string, value: string): void {
  if (!/[\\r\\n]/.test(value)) headers.set(name, value);
}

function response(format: 'text' | 'html' | 'json', body: string, status: number, headers: Headers): Response {
  if (!headers.has('content-type')) {
    headers.set(
      'content-type',
      format === 'html'
        ? 'text/html; charset=utf-8'
        : format === 'json'
          ? 'application/json; charset=utf-8'
          : 'text/plain; charset=utf-8'
    );
  }
  if (format === 'json') {
    try {
      return new Response(JSON.stringify(JSON.parse(body)), {status, headers});
    } catch {
      return new Response(JSON.stringify({error: 'invalid_generated_json'}), {
        status: 500,
        headers: {'content-type': 'application/json; charset=utf-8'}
      });
    }
  }
  return new Response(body, {status, headers});
}
`;
}

function routeSource(route: RouteIr, authMode: AuthMode): string {
  const method = route.method === 'ALL' ? 'all' : route.method.toLowerCase();
  const needsAuth = route.auth === 'required';
  const lines = [
    `app.${method}(${quote(route.path)}, async (c) => {`,
    '  let status = 200;',
    '  const headers = new Headers();',
    '  const handlerVariables = new Map<string, string>();',
    '  let requestBody: string | undefined;',
    '  let authUser: AuthUser | null = null;'
  ];
  if (needsAuth) {
    lines.push(
      `  authUser = await authenticate(c.req.raw, c.env, ${quote(authMode)});`
    );
    lines.push("  if (authUser === null) return c.json({error: 'unauthorized'}, 401);");
    lines.push("  c.set('authUser', authUser);");
  }
  for (const action of route.actions) lines.push(...actionSource(action));
  lines.push("  return c.json({error: 'handler_without_response'}, 500);");
  lines.push('});');
  return lines.join('\n');
}

function actionSource(action: ActionIr): string[] {
  if (action.kind === 'set-status') return [`  status = ${action.status};`];
  if (action.kind === 'set-header') {
    return [
      `  setResponseHeader(headers, ${quote(action.name)}, asText(${expressionSource(action.value)}));`
    ];
  }
  if (action.kind === 'remove-header') return [`  headers.delete(${quote(action.name)});`];
  if (action.kind === 'set-handler-variable') {
    return [
      `  handlerVariables.set(asText(${expressionSource(action.name)}), asText(${expressionSource(action.value)}));`
    ];
  }
  if (action.kind === 'change-handler-variable') {
    const name = `asText(${expressionSource(action.name)})`;
    return [
      `  handlerVariables.set(${name}, String(scratchNumber(handlerVariables.get(${name}) ?? '') + scratchNumber(${expressionSource(action.value)})));`
    ];
  }
  if (action.kind === 'delete-handler-variable') {
    return [`  handlerVariables.delete(asText(${expressionSource(action.name)}));`];
  }
  if (action.kind === 'clear-handler-variables') return ['  handlerVariables.clear();'];
  if (action.kind === 'respond') {
    return [`  return response(${quote(action.format)}, asText(${expressionSource(action.body)}), status, headers);`];
  }
  if (action.kind === 'record-create') {
    return [
      `  const ${action.result} = await createRecord(c.env.DB, ${quote(action.collection)}, asText(${expressionSource(action.data)}), authUserId(authUser));`
    ];
  }
  if (action.kind === 'record-list') {
    return [`  const ${action.result} = await listRecords(c.env.DB, ${quote(action.collection)});`];
  }
  if (action.kind === 'record-get') {
    return [`  const ${action.result} = await getRecord(c.env.DB, asText(${expressionSource(action.id)}));`];
  }
  return [`  const ${action.result} = await deleteRecord(c.env.DB, asText(${expressionSource(action.id)}));`];
}

function expressionSource(expression: ExpressionIr): string {
  if (expression.kind === 'literal') return quote(expression.value);
  if (expression.kind === 'concat') {
    return `asText(${expressionSource(expression.left)}) + asText(${expressionSource(expression.right)})`;
  }
  if (expression.kind === 'result') return expression.name;
  if (expression.kind === 'handler-variable') {
    return `handlerVariables.get(asText(${expressionSource(expression.name)})) ?? ''`;
  }
  if (expression.kind === 'handler-variable-exists') {
    return `handlerVariables.has(asText(${expressionSource(expression.name)}))`;
  }
  if (expression.kind === 'handler-variable-names') {
    return `Array.from(handlerVariables.keys()).join(',')`;
  }
  if (expression.kind === 'request-value') {
    if (expression.source === 'query') return `c.req.query(${quote(expression.name)}) ?? ''`;
    if (expression.source === 'path-param') return `c.req.param(${quote(expression.name)}) ?? ''`;
    return `c.req.header(${quote(expression.name)}) ?? ''`;
  }
  if (expression.source === 'method') return 'c.req.method';
  if (expression.source === 'path') return 'new URL(c.req.url).pathname';
  if (expression.source === 'url') return 'c.req.url';
  if (expression.source === 'body') return `(requestBody ??= await c.req.text())`;
  if (expression.source === 'content-type') return "c.req.header('content-type') ?? ''";
  return "c.req.header('cf-connecting-ip') ?? ''";
}

function indexSource(): string {
  return `import {Hono} from 'hono';
import {registerGeneratedRoutes, type Bindings, type Variables} from './routes.generated';

const app = new Hono<{Bindings: Bindings; Variables: Variables}>();
registerGeneratedRoutes(app);

export default app;
`;
}

function authSource(): string {
  return `import {createRemoteJWKSet, jwtVerify} from 'jose';

export type AuthMode = 'none' | 'cloudflare-access' | 'external-jwt';
export type AuthUser = {
  id: string;
  email?: string;
  name?: string;
  provider?: 'google' | 'microsoft' | 'github';
  claims: Record<string, unknown>;
};

type AuthEnv = {
  CF_ACCESS_TEAM_DOMAIN?: string;
  CF_ACCESS_AUD?: string;
  JWT_ISSUER?: string;
  JWT_AUDIENCE?: string;
  JWT_JWKS_URL?: string;
};

export async function authenticate(request: Request, env: AuthEnv, mode: AuthMode): Promise<AuthUser | null> {
  if (mode === 'none') return null;
  const token = mode === 'cloudflare-access'
    ? request.headers.get('cf-access-jwt-assertion')
    : bearerToken(request.headers.get('authorization'));
  if (!token) return null;
  const issuer = mode === 'cloudflare-access'
    ? required(env.CF_ACCESS_TEAM_DOMAIN, 'CF_ACCESS_TEAM_DOMAIN').replace(new RegExp('/$'), '')
    : required(env.JWT_ISSUER, 'JWT_ISSUER');
  const audience = mode === 'cloudflare-access'
    ? required(env.CF_ACCESS_AUD, 'CF_ACCESS_AUD')
    : required(env.JWT_AUDIENCE, 'JWT_AUDIENCE');
  const jwksUrl = mode === 'cloudflare-access'
    ? new URL('/cdn-cgi/access/certs', issuer)
    : new URL(required(env.JWT_JWKS_URL, 'JWT_JWKS_URL'));
  try {
    const {payload} = await jwtVerify(token, createRemoteJWKSet(jwksUrl), {issuer, audience});
    if (typeof payload.sub !== 'string') return null;
    const user: AuthUser = {id: payload.sub, claims: payload};
    if (typeof payload.email === 'string') user.email = payload.email;
    if (typeof payload.name === 'string') user.name = payload.name;
    if (payload.provider === 'google' || payload.provider === 'microsoft' || payload.provider === 'github') {
      user.provider = payload.provider;
    }
    return user;
  } catch {
    return null;
  }
}

function bearerToken(value: string | null): string | null {
  const match = value?.match(/^Bearer\\s+(.+)$/i);
  return match?.[1] ?? null;
}

function required(value: string | undefined, name: string): string {
  if (!value) throw new Error(\`Missing secret or variable: \${name}\`);
  return value;
}
`;
}

function storageSource(): string {
  return `export type StoredRecord = {
  id: string;
  collection: string;
  ownerId: string | null;
  data: unknown;
  createdAt: string;
  updatedAt: string;
};

type RecordRow = {
  id: string;
  collection: string;
  owner_id: string | null;
  data_json: string;
  created_at: string;
  updated_at: string;
};

export interface RecordStore {
  create(collection: string, dataJson: string, ownerId?: string): Promise<StoredRecord>;
  list(collection: string): Promise<StoredRecord[]>;
  get(id: string): Promise<StoredRecord | null>;
  delete(id: string): Promise<boolean>;
}

export interface AssetStore { get(key: string): Promise<R2ObjectBody | null> }
export interface ConfigStore { get(key: string): Promise<string | null> }
export interface CounterStore { increment(key: string, amount: number): Promise<number> }

export async function createRecord(db: D1Database, collection: string, dataJson: string, ownerId?: string): Promise<StoredRecord> {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();
  JSON.parse(dataJson);
  await db.prepare(
    'INSERT INTO records (id, collection, owner_id, data_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)'
  ).bind(id, collection, ownerId ?? null, dataJson, now, now).run();
  return {id, collection, ownerId: ownerId ?? null, data: JSON.parse(dataJson), createdAt: now, updatedAt: now};
}

export async function listRecords(db: D1Database, collection: string): Promise<StoredRecord[]> {
  const result = await db.prepare(
    'SELECT id, collection, owner_id, data_json, created_at, updated_at FROM records WHERE collection = ? ORDER BY created_at DESC LIMIT 100'
  ).bind(collection).all<RecordRow>();
  return result.results.map(fromRow);
}

export async function getRecord(db: D1Database, id: string): Promise<StoredRecord | null> {
  const row = await db.prepare(
    'SELECT id, collection, owner_id, data_json, created_at, updated_at FROM records WHERE id = ?'
  ).bind(id).first<RecordRow>();
  return row ? fromRow(row) : null;
}

export async function deleteRecord(db: D1Database, id: string): Promise<boolean> {
  const result = await db.prepare('DELETE FROM records WHERE id = ?').bind(id).run();
  return result.meta.changes > 0;
}

function fromRow(row: RecordRow): StoredRecord {
  return {
    id: row.id,
    collection: row.collection,
    ownerId: row.owner_id,
    data: JSON.parse(row.data_json),
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}
`;
}

function packageJson(ir: DeployIr): string {
  return `${JSON.stringify(
    {
      name: packageName(ir.name),
      private: true,
      type: 'module',
      scripts: {dev: 'wrangler dev', deploy: 'wrangler deploy', typecheck: 'tsc --noEmit'},
      dependencies: {hono: '^4.10.7', jose: '^6.1.0'},
      devDependencies: {'@cloudflare/workers-types': '^5.20260918.1', typescript: '^5.9.3', wrangler: '^4.40.2'}
    },
    null,
    2
  )}\n`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        lib: ['ES2022', 'WebWorker'],
        types: ['@cloudflare/workers-types'],
        strict: true,
        noEmit: true,
        skipLibCheck: true
      },
      include: ['src/**/*.ts']
    },
    null,
    2
  )}\n`;
}

function wrangler(ir: DeployIr): string {
  return `{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": ${quote(packageName(ir.name))},
  "main": "src/index.ts",
  "compatibility_date": "2026-09-01",
  "d1_databases": [
    {"binding": "DB", "database_name": ${quote(`${packageName(ir.name)}-db`)}, "database_id": "REPLACE_WITH_D1_DATABASE_ID", "migrations_dir": "migrations"}
  ],
  // Optional adapter bindings:
  // "r2_buckets": [{"binding": "ASSETS", "bucket_name": "REPLACE_WITH_R2_BUCKET"}],
  // "kv_namespaces": [{"binding": "CONFIG", "id": "REPLACE_WITH_KV_NAMESPACE_ID"}]
}
`;
}

function migration(): string {
  return `CREATE TABLE records (
  id TEXT PRIMARY KEY,
  collection TEXT NOT NULL,
  owner_id TEXT,
  data_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX records_collection_created_at ON records (collection, created_at);
CREATE INDEX records_owner_collection_created_at ON records (owner_id, collection, created_at);
`;
}

function devVars(mode: AuthMode): string {
  if (mode === 'cloudflare-access') return 'CF_ACCESS_TEAM_DOMAIN=https://example.cloudflareaccess.com\nCF_ACCESS_AUD=replace-me\n';
  if (mode === 'external-jwt') return 'JWT_ISSUER=https://issuer.example/\nJWT_AUDIENCE=replace-me\nJWT_JWKS_URL=https://issuer.example/.well-known/jwks.json\n';
  return '# No secrets are required for auth mode none.\n';
}

function generatedReadme(ir: DeployIr): string {
  const routeTable = ir.routes.map((route) => `| ${route.method} | \`${route.path}\` | ${route.auth} |`).join('\n');
  return `# ${ir.name}

Generated Cloudflare Workers + Hono application.

| Method | Path | Auth |
|---|---|---|
${routeTable}

## Setup

1. Run \`pnpm install\`.
2. Create a D1 database and replace \`REPLACE_WITH_D1_DATABASE_ID\` in \`wrangler.jsonc\`.
3. Run \`pnpm wrangler d1 migrations apply DB --local\` for local development.
4. Copy \`.dev.vars.example\` to \`.dev.vars\` and fill required auth values.
5. Run \`pnpm dev\`, then deploy explicitly with \`pnpm deploy\`.

Secrets must be configured with \`wrangler secret put\` or the Cloudflare dashboard; never commit \`.dev.vars\`.

## Storage adapters

- D1: record store (enabled by default).
- R2: binary assets; add the commented \`ASSETS\` binding when used.
- KV: read-heavy configuration/cache only; add the commented \`CONFIG\` binding when used.
- Durable Objects: intentionally not generated. Use only for exact counters or coordinated realtime state.

## Rollback

The generator does not modify the TurboWarp bridge. Stop deploying this generated project to return to the bridge workflow. To remove Cloudflare resources, first export data if needed, then use \`wrangler delete\`, \`wrangler d1 delete <database>\`, and the corresponding R2/KV delete commands for resources you created.
`;
}

function packageName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '') || 'turbowarp-worker';
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function indent(value: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return value.split('\n').map((line) => (line.length > 0 ? prefix + line : line)).join('\n');
}
